// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/authorization.proto

package authorization

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Authorization service

func NewAuthorizationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Authorization service

type AuthorizationService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authorization_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Authorization_PingPongService, error)
}

type authorizationService struct {
	c    client.Client
	name string
}

func NewAuthorizationService(name string, c client.Client) AuthorizationService {
	return &authorizationService{
		c:    c,
		name: name,
	}
}

func (c *authorizationService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Authorization.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authorization_StreamService, error) {
	req := c.c.NewRequest(c.name, "Authorization.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authorizationServiceStream{stream}, nil
}

type Authorization_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authorizationServiceStream struct {
	stream client.Stream
}

func (x *authorizationServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authorizationServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authorizationServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authorizationServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authorizationServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authorizationService) PingPong(ctx context.Context, opts ...client.CallOption) (Authorization_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Authorization.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authorizationServicePingPong{stream}, nil
}

type Authorization_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authorizationServicePingPong struct {
	stream client.Stream
}

func (x *authorizationServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authorizationServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authorizationServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authorizationServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authorizationServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authorizationServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Authorization service

type AuthorizationHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Authorization_StreamStream) error
	PingPong(context.Context, Authorization_PingPongStream) error
}

func RegisterAuthorizationHandler(s server.Server, hdlr AuthorizationHandler, opts ...server.HandlerOption) error {
	type authorization interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Authorization struct {
		authorization
	}
	h := &authorizationHandler{hdlr}
	return s.Handle(s.NewHandler(&Authorization{h}, opts...))
}

type authorizationHandler struct {
	AuthorizationHandler
}

func (h *authorizationHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuthorizationHandler.Call(ctx, in, out)
}

func (h *authorizationHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthorizationHandler.Stream(ctx, m, &authorizationStreamStream{stream})
}

type Authorization_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authorizationStreamStream struct {
	stream server.Stream
}

func (x *authorizationStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authorizationStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authorizationStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authorizationStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authorizationStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authorizationHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthorizationHandler.PingPong(ctx, &authorizationPingPongStream{stream})
}

type Authorization_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authorizationPingPongStream struct {
	stream server.Stream
}

func (x *authorizationPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authorizationPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authorizationPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authorizationPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authorizationPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authorizationPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
